[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/rain_forecast/*"
  to = "/rain_forecast/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 